# Generated by Django 4.1.7 on 2023-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Дела')),
                ('date_of_end', models.DateTimeField()),
                ('create', models.DateField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Список дел',
                'verbose_name_plural': 'Список дел',
            },
        ),
    ]
