# Generated by Django 4.1.7 on 2023-03-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotodo',
            old_name='create',
            new_name='created',
        ),
    ]
